# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build docker image and push to registry
    runs-on: ubuntu-18.04
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY }}/vicomtech/traction
      APP_NAME: motion-server
    steps:
    - uses: actions/checkout@v2

    - name: Extract tag name
      run: |
        echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "Tagging image with:" $TAG_NAME
  
  deploy:
    name: Call deploy hook
    runs-on: ubuntu-18.04
    needs: [ build ]
    env:
      APP_NAME: motion-server
      TAG_NAME: v1.0.0
    steps:
      - uses: tv-vicomtech/workflow-webhook@v1.1.0
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}?token=${{ secrets.WEBHOOK_TOKEN }}&image=${{ env.APP_NAME }}&tag=${{ env.TAG_NAME }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
